name: stdev
description: STDev project.

version: 1.0.2+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_fonts: ^2.3.0
  
  provider: ^6.0.3
  get_it: ^7.1.3
  get: ^4.6.5
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  flutter_spinkit: ^5.1.0
  connectivity: ^3.0.6
  animate_do: ^2.1.0
  iconsax: ^0.0.8
  shimmer: ^2.0.0
  flutter_svg: ^0.22.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  logger: ^1.1.0
  
flutter:
  uses-material-design: true
  assets:
   - assets/images/
